# =========================
# HY2-INBOUND-TLS — sing-box-ui
# Env: local / prod
# =========================

### POST Check
POST {{baseUrl}}{{apiPrefix}}/sing-box/hy2/tls/check
Content-Type: {{json}}

{
  "certificatePath": "/data/sing-box/certs/hy2.crt",
  "keyPath": "/data/sing-box/certs/hy2.key"
}

###

### POST Generate
POST {{baseUrl}}{{apiPrefix}}/sing-box/hy2/tls/generate
Content-Type: {{json}}

{
  "certificatePath": "{{singBoxCertsDir}}test/server.crt",
  "keyPath": "{{singBoxCertsDir}}test/server.key",
  "serverName": "my-domain.com",
  "overwrite": false
}

###
