services:
  sing-box:
    image: bi4nbn/sing-box:v1.11.15
    container_name: sing-box
    restart: unless-stopped
    command: ["run", "-c", "/etc/sing-box/config.json"]
    volumes:
      - ./data/sing-box:/etc/sing-box:ro
      - ./data/sing-box-state:/var/lib/sing-box
    ports:
      - "443:443/tcp"
      - "8443:8443/udp"
      - "${PORT_RANGE_START}-${PORT_RANGE_END}:${PORT_RANGE_START}-${PORT_RANGE_END}/tcp"
      - "${PORT_RANGE_START}-${PORT_RANGE_END}:${PORT_RANGE_START}-${PORT_RANGE_END}/udp"
      -  # Для V2Ray API
      - "8080:8080"
    env_file:
      - .env

  ui:
    image: ghcr.io/zaymovskey/sing-box-ui:latest
    container_name: sing-box-ui
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/sing-box:/etc/sing-box
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    depends_on:
      - sing-box
