services:
  sing-box:
    build:
      context: ..
      dockerfile: docker/sing-box/Dockerfile
      args:
        SING_BOX_REF: v1.14.0-alpha.9
    image: local/sing-box:v1.14.0-alpha.9-v2ray-api
    container_name: sing-box
    restart: unless-stopped
    command: ["run", "-c", "/etc/sing-box/config.json"]
    volumes:
      - ../../data/sing-box:/etc/sing-box:ro
      - ../../data/sing-box-state:/var/lib/sing-box
    network_mode: host
    env_file:
      - .env

  worker:
    image: ghcr.io/zaymovskey/sing-box-ui-worker:${IMAGE_TAG:-latest}
    env_file:
      - .env
    volumes:
      - ../../data:/data
    restart: unless-stopped
    depends_on:
      - sing-box
    network_mode: host

  ui:
    image: ghcr.io/zaymovskey/sing-box-ui:${IMAGE_TAG:-latest}
    container_name: sing-box-ui
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    volumes:
      - ../../data/sing-box:/etc/sing-box
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../data:/data
    ports:
      - "3000:3000"
    depends_on:
      - sing-box
